### ISSUE TITLE
Planning > Advertising and RSVP

### ISSUE THREAD

**Issue by shannylu** [YEGDevStories/YEGDevStories-Meetup#14]
1. Create short blurb about event and if required, details about RSVP etc. Post this blurb to meet up for online advertising.
2. Check the list of people that have RSVPed – On meetups.com (Edmonton)
3. Make sure reminders are set up for people that have RSVPed

**Comment by djphan** [comment]
Advertising has been done through social media, U of A, and Meetup.com
