### ISSUE TITLE
Planning > Food and refreshments > Food ordering

### ISSUE THREAD

**Issue by shannylu** [YEGDevStories/YEGDevStories-Meetup#15]
Based upon budget and RSVP numbers, order food and refreshments ~48-24 hours in advance. Also consider: napkins, plates, cups etc. Account for some extra people that may come to the event – particularly if advertising was more ‘last minute’.

Arrange to pick-up or have someone pick up food/drinks etc. and arrive at event location ~one hour before event

**Comment by djphan** [comment]
Food ordered and ready to go
