### ISSUE TITLE
Planning > Evaluation > Survey

### ISSUE THREAD

**Issue by shannylu** [YEGDevStories/YEGDevStories-Meetup#21]
Prepare feedback/survey form on meetup.com under our account

**Comment by danAtInv** [comment]
Survey link:
https://www.surveymonkey.com/r/3M3D2XF

Shortened link:
https://goo.gl/p5gRo3

**Comment by danAtInv** [comment]
Survey created.  Let me know if any changes are desired.  I linked it from the event description on meetup.com.
