### ISSUE TITLE
Outreach to find a new venue to host the meetup

### ISSUE THREAD

**Issue by djphan** [YEGDevStories/YEGDevStories-Meetup#26]
Lets try and find a new venue

**Comment by djphan** [comment]
The Delta and also the Holiday Inn have conference rooms for about $300/day to accommodate larger groups

**Comment by SteveReiter** [comment]
Does anyone have the contact info for the UA Faculty of Extension? It worked out well, I think we should go with them again.

**Comment by djphan** [comment]
https://github.com/djphan/Large-Scale-Web-Developement-Meetup/wiki/Resources-and-Contacts Has the information now

**Comment by shannylu** [comment]
I logged all the information in the last meeting notes we have before the event. Looks like Dan Phan has got it.

Regards,
Shanny
