### ISSUE TITLE
Rebranding

### ISSUE THREAD

**Issue by SteveReiter** [YEGDevStories/YEGDevStories-Meetup#27]
We need to come up with some ideas for a new name. Focus should be on real-world examples/experiences with technologies and processes.

**Comment by djphan** [comment]
Some initial Investigations:
* Dev Stories is a theme that has been used in some other meetups
* Focused nights would be of interest. People would go to meetups in their own area of expertise (e.g QA for QA, Web Dev for Web Dev)
* Want to come up with program agnostic themes to fit the themes from Polyglot (e.g. Testing will draw QA and Devops/QA/Automation Devs)
* General interest is piqued.

**Comment by SteveReiter** [comment]
YEGDevStories it is!
