### ISSUE TITLE
Contact Tammy Lee about yegdev slack

### ISSUE THREAD

**Issue by SteveReiter** [YEGDevStories/YEGDevStories-Meetup#28]
Can we use yegdev slack and push or attendees to use it?

It would be nice if it had a simpler method of getting on, currently you have to contact tammy lee on twitter. The calgary dev slack has a self-serve page to gain access.

**Comment by djphan** [comment]
Tl:DR of meeting:
* Current Slack is for devs specifically
* Want to establish a vetting process where devs vet other devs before joining the Slack
* Need to discuss if we want to create a fully open YEG Tech Slack OR use the YEG Dev Slack at its current conditions and setup something else down the line when we want to expand.
* Currently focused for Devs for the planned meetup date

**Comment by SteveReiter** [comment]
We're going to setup our own slack for now. #37
