### ISSUE TITLE
Planning > Event > Create agenda/outline of event and distribute to volunteers

### ISSUE THREAD

**Issue by shannylu** [YEGDevStories/YEGDevStories-Meetup#9]
Create agenda/outline of event and distribute to volunteers

**Comment by djphan** [comment]
Tentative Itinerary for the meetup. Everyone else please take a look and provide feedback
5:00pm we start setting up
6:30pm doors open, food/drinks/mingle
7:00pm Masha begins presentation, Q&A
~7:30pm (Optional) Intermission, food, drinks, bathroom
7:45pm(at the latest) I'll start presenting
8:15pm I'll be done, mingle, food, drinks
9:00pm send everyone home
